language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pylint -E aztk
  - pytest --ignore=tests/spark/integration_tests

branches:
  only:
  - master
